# Generated by Django 3.0.4 on 2020-05-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_announcement_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Anúncio', 'verbose_name_plural': 'Anúncios'},
        ),
    ]
